name = "maasga-website"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "maasga_db"
database_id = "2317adea-fdbe-4597-b64d-11d68d03b63b"

[env.preview]
vars = { ENVIRONMENT = "preview" }
